[package]
name = "rs-evaluator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.74"
lib-ir = { path = "../lib-ir" }

[lib]
crate-type = ["cdylib"]
